ecommerce/main/routes.py
from flask import Blueprint, render_template, jsonify, request
from ecommerce import mongo
from flask_login import current_user
from bson.objectid import ObjectId
import json
from bson.json_util import dumps

main = Blueprint('main', __name__)
global gender
gender = None


def ret_brands(Category=None, Type=None):
  if(Category != None and Type != None):
    brands = mongo.db.items.distinct('Brand', {'Category': Category, 'Type': Type})
  elif(Category != None):
    brands = mongo.db.items.distinct('Brand', {'Category': Category})
  else:
    brands = mongo.db.items.distinct('Brand', {'Type': type})

  return brands


def ret_categories(category):
  categories = mongo.db.items.distinct('Type', {'Category': category})
  return categories


@main.route('/items/gender', methods=['POST'])
def update_home():
  gender = request.json
  categories = ret_categories(gender)
  #items = mongo.db.items.find({'Category': gender})
  brands = ret_brands(gender)
  return render_template('categories_brands.html', brands=brands, categories=categories,gender=gender)


@main.route('/', defaults={'type': 'Shirt'})
@main.route('/<string:type>')
def home(type):
  mongo.db.items.find_one_or_404({'Type': type.title()})  # just to return 404 error if there is not a single item with that thing
  items = mongo.db.items.find({'Type': type.title()})
  global itemType
  itemType = type  # so that same type of items are getched in filter results
  brands = ret_brands(type)
  categories = ret_categories('Men')
  types = mongo.db.items.distinct('Type')
  return render_template('home.html', items=items, brands=brands, categories=categories, itemType=type.title(), types=types)


@main.route('/newhome')
def newhome():
  itemsb = mongo.db.items.find({'Type': 'Bedsheet'}).limit(12)
  itemst = mongo.db.items.find({'Type': 'Top'}).limit(12)
  itemsd = mongo.db.items.find({'Type': 'Dress'}).limit(12)
  itemss = mongo.db.items.find({'Type': 'Shirt'}).limit(12)

  return render_template('newhome.html', itemsb=itemsb, itemst=itemst, itemsd=itemsd, itemss=itemss)


@main.route('/items/filter', methods=['POST'])
def filter():
  minDiscount = 0
  maxPrice = 10000
  print('here')

 # print(request.json)
  brands = request.json['Brand']
  types = request.json['Type']

  Gender=request.json['Gender']


  print('brands: ', len(brands))
  if(request.json["Price"]):
    maxPrice = 100
    for price in request.json['Price']:
      maxPrice = max(maxPrice, price)
  if(request.json["Discount"]):
    minDiscount = 100
    for discount in request.json['Discount']:
      minDiscount = min(minDiscount, discount)
  print('maxPrice is ', maxPrice)
  if(len(Gender)==0 and len(types) == 0 and len(brands)==0 ):
     items = mongo.db.items.find(
      {'$and': [
          {'Price': {'$lte': maxPrice}},
          {'Discount': {'$gte': minDiscount}}
      ]
      })

  if(len(Gender)==0 and len(types) == 0 and len(brands)!=0):
     items = mongo.db.items.find(
      {'$and': [
          {'$or': brands},
          {'Price': {'$lte': maxPrice}},
          {'Discount': {'$gte': minDiscount}}
      ]
      })

  elif(len(Gender)==0 and len(types)!=0 and len(brands)==0 ):
    print('dogy')
    items = mongo.db.items.find(
      {'$and': [
          {'$or': types},
          {'Price': {'$lte': maxPrice}},
          {'Discount': {'$gte': minDiscount}}
      ]
      })

  elif(len(Gender)==0 and len(types)!=0 and len(brands)!=0):
     items = mongo.db.items.find(
      {'$and': [
          {'$or': types},
          {'$or': brands},
          {'Price': {'$lte': maxPrice}},
          {'Discount': {'$gte': minDiscount}}
      ]
      })

  elif(len(Gender)!=0 and len(types)!=0 and len(brands)==0 ):
     items = mongo.db.items.find(
      {'$and': [
          {'Category': gender},
          {'$or':types},
          {'Price': {'$lte': maxPrice}},
          {'Discount': {'$gte': minDiscount}}
      ]
      })

  elif(Gender is not  None and len(types)!=0 and len(brands)!=0):
     items = mongo.db.items.find(
      {'$and': [
          {'Category': Gender},
          {'$or':types},
          {'$or':brands},
          {'Price': {'$lte': maxPrice}},
          {'Discount': {'$gte': minDiscount}}
      ]
      })

  elif(len(Gender)!=0 and len(types) == 0 and len(brands)==0 ):
    print('entering')
    items = mongo.db.items.find(
      {'$and': [
          {'Category': Gender},
          {'Price': {'$lte': maxPrice}},
          {'Discount': {'$gte': minDiscount}}
      ]
      })

  elif(len(Gender)!=0 and len(types) == 0 and len(brands)!=0):
    print('yippy')
    print(gender)
    items = mongo.db.items.find(
      {'$and': [
          {'Category': Gender},
          {'$or':brands},
          {'Price': {'$lte': maxPrice}},
          {'Discount': {'$gte': minDiscount}}
      ]
      })

  return render_template('home_items.html', items=items)
  # return(dumps(items))


@main.route('/item/<string:item_id>')
def item(item_id):
  item = mongo.db.items.find_one_or_404({"_id": ObjectId(item_id)})
  reviews_exist = mongo.db.review.find({'item_id': ObjectId(item_id)}, {'_id': 0, 'reviews': 1}).count()
  similar_products = mongo.db.items.find({'Category': item['Category'], 'Type': item['Type']}).limit(10)
  if reviews_exist:
    reviews_dict_cursor = mongo.db.review.aggregate([{'$project':
                                                      {
                                                          'rating_avg': {'$avg': '$reviews.rating'},
                                                          'number': {'$size': '$reviews'},
                                                          'reviews': '$reviews'
                                                      }
                                                      }])
  else:
    reviews_dict_cursor = None
  return render_template('item.html', item=item, reviews_cursor=reviews_dict_cursor, title=item['Description'], similar_products=similar_products)


@main.route('/search_results', methods=['GET'])
def search():
  search_input = request.args.get("q")
  search_result_count = mongo.db.items.find({'$text': {'$search': search_input}}).count()
  if search_result_count:
    search_results = mongo.db.items.find({'$text': {'$search': search_input}})
  else:
    search_results = None
  return render_template('search.html', count=search_result_count, items=search_results)


@main.route('/seller')
def seller():
  return render_template('sellerdashboard.html')

ecommerce/users/routes.py
import math,string,secrets
import flask_admin as admin
from datetime import datetime, timedelta
from flask import render_template, redirect, url_for, Blueprint, flash, request, redirect, send_from_directory
from werkzeug.security import generate_password_hash, check_password_hash
from flask_login import current_user, login_required, login_user, logout_user
from ecommerce.users.forms import RequestResetForm, ResetPasswordForm, RegistrationForm, LoginForm, DeliveryForm, ReviewForm
from ecommerce.seller.forms import SellerForm
from ecommerce.seller.forms import ItemForm
from ecommerce.users.utils import send_reset_email, sendPasswordSeller
from ecommerce import db, bcrypt, mongo
from ecommerce.models import User
import json
from bson.objectid import ObjectId
import os
from functools import wraps
from bson.json_util import dumps



users = Blueprint('users', __name__)
APP_ROOT = os.path.dirname(os.path.abspath(__file__))


@users.route('/register', methods=['GET', 'POST'])
def register():
    if current_user.is_authenticated:
        return redirect(url_for('main.home'))
    form = RegistrationForm()
    if form.validate_on_submit():
        existing_user = User.objects(email=form.email.data).first()
        if existing_user is None:
            hashpass = generate_password_hash(form.password.data,method='sha256')
            role = 'customer'
            if form.seller.data:
                role= 'seller'
                approved=0
                User(form.username.data, form.email.data, hashpass,role,approved).save()
                flash('Your registeration is successfull.', 'success')
                form=SellerForm()
                if(form.validate_on_submit()):
                    return render_template('registration(part-3).html',title='Completed')
                return render_template('seller_registration.html',title='Step 2',form=form)
                    
            else:
                User(form.username.data, form.email.data, hashpass,role).save()



            flash('Your account has been created. You are now able to log in.', 'success')
        return redirect(url_for('users.login'))
    return render_template('register.html', title='register', form=form)


def roles_required(f):
  @wraps(f)
  def decorated_function(*args, **kwargs):
    id = current_user.get_id()
    print('user id : ', id)
    user= mongo.db.user.find_one({"_id": ObjectId(id)})
    print(user)
    print(user['email'], " ", user['role'])
    if user['role'] == 'customer' or user['role']=='seller':
      flash('You are not an admin')
      return render_template('errors/403.html'), 403


    return f(*args, **kwargs)
  return decorated_function


@users.route('/login', methods=['GET', 'POST'])
def login():
    if current_user.is_authenticated:
        return redirect(url_for('main.home'))
    form = LoginForm()
    if form.validate_on_submit():
        check_user = User.objects(email=form.email.data).first()
        if check_user and check_password_hash(check_user['password'], form.password.data):
            login_user(check_user)
            #id = current_user.get_id()
            #user_document=mongo.db.user.find_one({'_id':ObjectId(id)},{'_id':0,'role':1})
            #if user_document['role']=='admin':
             #   return redirect('/admin_')
            flash('You have been successfully logged in', 'success')
            next_page = request.args.get('next')
            return redirect(next_page) if next_page else redirect(url_for('main.home'))
        else:
            flash('Login Unsuccessful, Please check email and password', 'danger')
    return render_template('login.html', title='login', form=form)


@users.route('/logout')
def logout():
    logout_user()
    return redirect(url_for('main.home'))

@users.route('/admin_')
@login_required
@roles_required
def admin():
    #Admin = admin(current_app)

    print(current_user.get_id())
    print("yessssssssssssssssssssssssssssss")
    approvedSellers=mongo.db.user.find({'role':'seller','approved':True})
    unapprovedSellers=mongo.db.user.find({'role':'seller','approved':False})
    
    return render_template('admin_portal.html',title='Admin portal',approvedSellers=approvedSellers,unapprovedSellers=unapprovedSellers)


@users.route('/seller/approved/<string:seller_id>', methods=['POST'])

# @login_required
# @roles_required
def seller_approved(seller_id):
    #Admin = admin(current_app)

    print(seller_id)
    print("nnnnnnnssssssssssssssssssssssssssssss")
    # generating password to be sent to seller that contains atleast 1 lowercase, uppercase, digit, punctiation
    passwordSource= string.ascii_letters +string.digits +string.punctuation
    password= secrets.choice(string.ascii_lowercase)
    password+=secrets.choice(string.ascii_uppercase)
    password+=secrets.choice(string.digits)
    password+=secrets.choice(string.punctuation)
    print('Data')    
    for i in range(0,6):
        password+=secrets.choice(passwordSource)
    hashpass = generate_password_hash(password,method='sha256')
    sellerDocument=mongo.db.user.find_one({'_id':ObjectId(seller_id)},{'_id':0,'email':1})

    #sending password to seller 
    #sendPasswordSeller(sellerDocument['email'],password)
    print('is')
    '''
    mongo.db.user.update_one({'_id':ObjectId(seller_id)},
        {
        '$set':
            {
                'approved':True,
                'password':hashpass,

            }
        })
    '''
    print('here')
    sellers=mongo.db.user.find({'role':'seller', 'approved':False})
    sellersJson=dumps(sellers)
    return sellersJson


    






@users.route('/add_wishlist/<string:item_id>', methods=['GET', 'POST'])
@login_required
def add_to_wishlist(item_id):
    id = current_user.get_id()
    item = mongo.db.user.find({'_id': ObjectId(id), 'wishlist.item_id': ObjectId(item_id)}).count()
    if item == 0:
        itemdetail = mongo.db.items.find_one({'_id': ObjectId(item_id)})
        a = {"item_id": ObjectId(item_id)}
        mongo.db.user.update_one(
            {"_id": ObjectId(id)
             },
            {"$push":
             {"wishlist": a
              }
             }
        )
        flash('This item has been successfully added to yor wishlist', 'success')
    else:
        flash('This item is already present in your wishlist', 'success')
    return redirect(url_for('main.home'))


@users.route('/removing/<string:item_id>', methods=['GET', 'POST'])
@login_required
def remove_from_wishlist(item_id):
    id = current_user.get_id()
    mongo.db.user.update_one(
        {"_id": ObjectId(id),
         },
        {"$pull":
            {"wishlist":
                {
                    "item_id": ObjectId(item_id),
                }
             }
         }
    )
    flash('Successfully Removed', 'success')
    return redirect(url_for('users.wishlist'))

@users.route('/my_wishlist', methods=['GET', 'POST'])
@login_required
def wishlist():
    id = current_user.get_id()
    result_cursor = mongo.db.user.aggregate([{'$match': {'_id': ObjectId(id)}},
                                  {'$project':
                                   {'_id': 0, 'wishlist': 1, 'count':
                                    {'$size': '$wishlist'}
                                    }
                                   }
                                  ])
    for result in result_cursor:
        if result['count']>0:
            count=result['count']
            print(count)
            items = mongo.db.user.aggregate([
                {'$match': {'_id': ObjectId(id)}},
                {'$lookup':
                 {
                     'from': 'items',
                     'localField': 'wishlist.item_id',
                     'foreignField': '_id',
                     'as': 'item_info'
                 }
                 },
                {'$project': {'_id':0,'item_info.Category':1,'item_info._id': 1, 'item_info.Type': 1, 'item_info.Category': 1, 'item_info.Color': 1, 'item_info.Seller': 1, 'item_info.Image': 1, 'item_info.Brand': 1, 'item_info.Short Description': 1, "item_info.Price":1,"item_info.Discount":1},
                 }
            ])
            break
        else:
            count=0
            items=None
            print(count)
            break
    if(items):
        for item in items:
            items=item["item_info"]
    else:
        items=None
    return render_template('wishlist.html',items_dict=items,count=count)
@users.route('/saving/<string:item_id>', methods=['GET', 'POST'])
@login_required
def add_to_cart(item_id):
    id = current_user.get_id()
    item = mongo.db.user.find({'_id': ObjectId(id), 'item.item_id': ObjectId(item_id), 'item.size': request.form['si']}).count()
    if item==0:
        print(request.form['si'])
        itemdetail=mongo.db.items.find_one({'_id':ObjectId(item_id)})
        #this comment is to be removed on using with mlab (online databse)
        #a = {"item_id":ObjectId(item_id), "size": request.form['si'], "quantity": 1,"SellerId":itemdetail['SellerId']}
        a = {"item_id":ObjectId(item_id), "size": request.form['si'], "quantity": 1}
       
        mongo.db.user.update_one(
            {"_id": ObjectId(id)
             },
            {"$push":
             {"item": a
              }
             }
        )
        flash('This item has been successfully added to cart', 'success')
    else:
        flash('This item is already present in your cart', 'success')
    return redirect(url_for('main.home'))


@users.route('/updating/<string:item_id>/<string:item_attr>', methods=['GET', 'POST'])
@login_required
def update_cart(item_id, item_attr):
    id = current_user.get_id()
    # item=mongo.db.items.find_one({'_id': ObjectId(item_id)}, {"_id": 0, "Size": 1})
    # size=item["Size"]
    print(item_id)
    print('nefjef')
    print(item_attr)
    print(type(item_attr))
    if('qt' in request.form):
        mongo.db.user.update_one(
            {
                        "_id": ObjectId(id),
                        "item":

ecommerce/templates/admin_portal.html
{% extends "layout.html" %}
{% block content %}
<div class="container">
	<button  id ="btn-1" class="w3-btn w3-pink"> Approved Sellers </button>
	<button id="btn-2" class="w3-btn w3-pink"> Unapproved Sellers </button>
	
 	<div class="sellers approved-sellers">
		<h2> Approved Sellers</h2>
		{% for seller in approvedSellers %}
		
			<div id ="{{seller['_id']}}" class="full-box text-muted">
	  
					<h4> <b> Name: </b>{{seller['username']}}</h4>
		  			<br>
		  			<h4> <b> Email Id: </b>{{seller['email']}} </b> </h4>
		  
		 				
			<!-- <input type="checkbox" data-width="200"  data-toggle="toggle" data-on="Approved" data-off="Not Approved" id="cb" data-onstyle="success" data-offstyle="danger">
		 -->
			</div>
			<div id="converted-seller">
			</div>
		{% endfor %}
	</div>
 
	<div class="sellers unapproved-sellers">
		<h2>Unapproved Sellers</h2>
		{% for seller in unapprovedSellers %}
		
			<div id ="{{seller['_id']}}" class="full-box text-muted">
	  
					<h4> <b> Name: </b>{{seller['username']}}</h4>
		  			<br>
		  			<h4> <b> Email Id: </b>{{seller['email']}} </b> </h4>
		  
		 			<label class="Checkbox">Approve
		 				<input type="checkbox" id="cb" unchecked value="{{seller['_id'] }}" >
		 				<span class="checkmark"></span>
					</label> 			
			<!-- <input type="checkbox" data-width="200"  data-toggle="toggle" data-on="Approved" data-off="Not Approved" id="cb" data-onstyle="success" data-offstyle="danger">
		 -->
		</div>
				{% endfor %}
	</div>
</div>  

<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"> </script>

<script type="text/javascript">
	$(function(){

		$('.sellers').hide();
		console.log('yippy');
		$('#btn-1').on('click',function(){
				console.log('clicked');
				$('.unapproved-sellers').hide();
				$('.approved-sellers').slideToggle(1000);

		});

		$('#btn-2').on('click',function(){
				$('.approved-sellers').hide();
				 $('.unapproved-sellers').slideToggle(1000);

		});
		$("input").on("click",function(){
		console.log('arora');
		var $sellerId=$(this).parent().parent();
		console.log('mohit');
		console.log('done',$sellerId);
		$sellerId.delay(10000000).remove();
			data={
				sellerCheckedId:$(this).val(),
				};

			$.ajax({
				type:"POST",
				data:data,
				url:'/seller/approved/'+data.sellerCheckedId,
				success:function(sellers){
					 $sellerId.slideUp(1000).delay(1000).slideDown(1000).fadeOut(1000).remove();
					console.log(sellers);
					

				}

			})

		});
	});
	// 	// console.log('Mohit');
	// 	// $("#cb").change(function(){
	// 	// 	var status = document.getElementById('cb');
	// 	// 	if (cb.checked) {
	// 	// 		var data = {
	// 	// 			id: $("#cb").val(),
	// 	// 		};
	// 	// 		// data.id = $("#cb").val();
	// 	// 		console.log(data.id);
	// 	// 		console.log('dyessssssss');

	// 			$.ajax({
	// 				type: "POST",
	// 				data:data,
	// 				contentType: 'application/json',
	// 				url: '/seller/approved/'+data.id,
	// 				success:function(sellers)
	// 				{
	// 					console.log(sellers);
	// 				},
					
	// 			});

	// 		}
			
	// 		else	{

	// 		}

	// 	});
	// });
</script>>

{% endblock content %}

ecommerce/templates/checkout.html
<br><br><br>

{% extends "style.html" %}
{% block content %}
<div class="container">
<ul class="inline font-weight-bold">
  <span class="left">
    <li><a href=" {{url_for('main.home')}} ">Smart Shop</a></li>

   </span>
   <span class="right">
      <i class="fa fa-lock grey" style="font-size:24px"></i> <small> 100%  SECURE</small>
    </span>
   <div class="center">
    <li><a href="{{url_for('users.cart')}}">Bag</a></li>
    <li>........</li>
    <li class="underline orange"><a href="#">Delivery</a></li>
    <li>........</li>
    <li>Payment</li>
    </div>

</ul>
<hr>
  <form name="a" action="{{ url_for('users.place_order') }}" method="post">
  <div class="seventy">
  <h5 class="font-weight-bold">Select Delivery Address</h5>
  {% for address in list_address %}
    <label class="equal-container" id="box-hover">
          <input type="radio" value={{loop.index-1}} name="address_number" required><p> {{address["name"] }}</p>
            <small class="text-muted" id="des">{{address["address"]}} <br> {{address['city']}}-{{address['pin-code']}}<br>{{address['state']}}<br><br>Mobile: <b> {{address['phone_number']}}</b></small>
            <br>
            <a class="btn btn-success btn-md" href="{{ url_for('users.remove_address', number=loop.index-1) }}">Remove</a>
           <a class="btn btn-success btn-md" href="#">Edit</a>
      </label>
{% endfor %}
    <div class="equal-container" id="box-hover">
      <span class="center">
        <h2><a class="btn btn-default btn-circle" href="{{ url_for('users.address') }}"><b>+</b></a> <a  href="{{ url_for('users.address') }}">Add new address</a></h2>
      </span>
      </div>
  </div>


  <div class="twenty" style="margin-top:30px" >
  <br>
  <small class="text-muted">Estimated Delivery:{{delivery_date.day }} {{delivery_date.strftime("%B")}}  {{delivery_date.year}}</small>
  <br>
      <b>{{number}}
      {% if number==1 %}
        ITEM
      {% else %}
        ITEMS
      {% endif %}
      </b>
      <hr>
      <h5>Bag Total<span class="right">Rs.{{dict["bag_mrp"]}}</span></h5>
      <h5>Bag Discount <span class="right">-Rs.{{dict["bag_discount"]}}</span></h5>
      <h5>Estimated Tax<span class="right"> {{dict['tax']}}</span></h5>
      {% if dict['delivery']==0 %}
        <h5>Delivery Charges<span class="right">Free</span></h5>
      {% else %}
        <h5>Delivery Charges<span class="right">{{dict['delivery']}}</span></h5>
      {% endif %}
      {% if dict['bag_offer_discount']!=0 %}
         <h5>Offer Discount <span class="right">-Rs.{{dict["bag_offer_discount"]}}</span></h5>
      {% endif %}
      <hr>
      <h3><b>Total Payable</b><span class="right"><b>Rs.{{dict['order_total']}}</b></span></h3>
        <input type=submit value="Place Your Order Now" class="btn btn-success btn-block btn-md" onclick="this.disabled=true;this.value='Sending, please wait...';this.form.submit();" >

        <br>
        <br>
  </form>
  </div>
</div>
{% endblock content %}

ecommerce/templates/home_items.html
{% for item in items %}

  <div class="box">
    <a href="{{ url_for('main.item', item_id=item['_id']) }}">
            <img class="rounded article-image" width="220" height="280" src= " {{ url_for('static', filename=item['Category']+'/'+item['Image'][0]) }}">
    </a>
    <h5><b>{{item["Brand"] }}</b></h5>
            <small class="text-muted" id="des">{{item["Short Description"]}}</small><br>
             <strong> Rs.{{item["Price"] }} </strong>
            {% if item["Discount"] !=0 %}
                <strike class="text-muted"> <small>Rs.{{item["Mrp"] }} </small></strike>  &nbsp;
              <font  color="#FF4500" >  ({{item["Discount"]}}% OFF)</font>
            {% endif %}
            <br><br>
             <a class="w3-btn w3-pink" href="{{ url_for('users.add_to_wishlist',item_id=item['_id']) }}">Add to wishlist </a>

  </div>
{% endfor %}

ecommerce/templates/orderreceived.html
{% extends "layout.html"%}
{%block content%}
<div class="row">
{%for order in ordersr%}

    <div class="wrapper">
    <div class ="sel_item_image_view">
    <img style="margin: 20px" width="100" height="100" src= " {{ url_for('static', filename=order[0]['Category']+'/'+order[0]['Image'][0]) }}">
    </div>
    <div class="sel_item_info">
    <h5> <a   href="{{ url_for('main.item',item_id=order[0]['_id'] ) }}">{{order[0]["Brand"] }}</a> </h5>
    <p>Size : {{order[1]['size']}}</p>
    <p>Quantity : {{order[1]['quantity']}}</p>
    <p>Amount to be recieved : {{order[1]['price']}}</p>
    <p>
        customer address:
        Name: {{order[2]['name']}}
        Address: {{order[2]['address']}}
        City: {{order[2]['city']}}
        Pincode: {{order[2]['pin_code']}}
        State: {{order[2]['state']}}
        Phone No: {{order[2]['phone_number']}}

    </p>
    </div>
    </div>

{%endfor%}
</div>


{% endblock content %}

ecommerce/templates/registration(part-3).html
{% extends "layout.html" %}
{% block content %}
<h4><b> Your application is completed. Your account info has been sent to admin for authorization. You will be notified soon through email.<br>
	Thank You!
</b></h4>


{% endblock content %}

ecommerce/templates/reset_request.html
{% extends "layout.html" %}
{% block content %}
	<div class="container">
	<div class="middle fifty-box">
		<form method="Post" action="">
		{{ form.hidden_tag()  }}
				<legend class="border-bottom mb-4">Reset Password</legend>
				<div class="form-group">
					{{ form.email.label(class="form-control-label")}}

					{% if form.email.errors %}
						{{ form.email(class="form-control form-control-lg is-invalid")}}
						<div class="invalid-feedback">
								{% for error in form.email.errors %}
									<span> {{ error }} </span>
								{% endfor %}
						</div>
					{% else %}
						{{ form.email(class="form-control form-control-lg") }}
					{% endif %}
				</div>
					
				<div class="form-group">
				{{ form.submit(class="btn btn-outline-info")}}
				</div>
		</form>
	</div>
	</div>

{% endblock content %}

ecommerce/templates/reset_token.html
{% extends "layout.html" %}	
{% block content %}
	<div class="container">
		<div class="middle fifty-box">
			<form method="Post" action="">
			{{ form.hidden_tag()  }}
				<legend class="border-bottom mb-4">Reset Password</legend>
				<div class="form-group">
					{{ form.password.label(class="form-control-label")}}

					{% if form.password.errors %}
						{{ form.password(class="form-control form-control-lg is-invalid")}}
						<div class="invalid-feedback">
								{% for error in form.password.errors %}
									<span> {{ error }} </span>
								{% endfor %}
						</div>
					{% else %}
						{{ form.password(class="form-control form-control-lg") }}			
					{% endif %}
				</div>
				<div class="form-group">
					{{ form.confirm_password.label(class="form-control-label")}}

					{% if form.confirm_password.errors %}
						{{ form.confirm_password(class="form-control form-control-lg is-invalid")}}
						<div class="invalid-feedback">
								{% for error in form.confirm_password.errors %}
									<span> {{ error }} </span>
								{% endfor %}
						</div>
					{% else %}
						{{ form.confirm_password(class="form-control form-control-lg") }}			
					{% endif %}
				</div>
			<div class="form-group">
				{{ form.submit(class="btn btn-outline-info")}}	
			</div>
		</form>
	
	<div class="border-top pt-3">
		<small class="text-muted">
			Need an Account? <a class="ml-2" href=" {{ url_for('users.register') }}"> Sign Up Now </a>
		</small>
	</div>
</div>
</div>
	
{% endblock content %}

ecommerce/templates/wishlist.html
{% extends "layout.html" %}
{% block content %}
<br><br>
<div class="container">
{% if count == 0 %}
  <span class="center"><h3 class="font-weight-bold">Your Wishlist is empty. </h3></span>
{% else %}
<div class="eighty">
{% for item in items_dict %}
   <div class="box">
       <a href="{{ url_for('main.item', item_id=item['_id']) }}">
            <img class="rounded article-image" width="220" height="280" src= " {{ url_for('static', filename=item['Category']+'/'+item['Image'][0]) }}">
    </a>
      <h5><b>{{item["Brand"] }}</b></h5>
              <small class="text-muted" id="des">{{item["Short Description"]}}</small><br>
               <strong> Rs.{{item["Price"] }} </strong>
              {% if item["Discount"] !=0 %}
                  <strike class="text-muted"> <small>Rs.{{item["Mrp"] }} </small></strike>  &nbsp;
                <font  color="#FF4500" >  ({{item["Discount"]}}% OFF)</font>
              {% endif %}
              <br><br>
              <a class="w3-btn w3-red" href=" {{url_for('users.remove_from_wishlist',item_id=item['_id']) }}">Remove</a></br>
    </div>
{% endfor %}

</div>
{% endif %}
</div>
{% endblock content %}